apiVersion: v1
kind: ConfigMap
metadata:
  name: autocarehub-config
  namespace: autocarehub
data:
  POSTGRES_DB: autocarehub
  POSTGRES_USER: autocarehub
  PGDATA: /var/lib/postgresql/data/pgdata
  DB_URL: jdbc:postgresql://autocarehub-postgres:5432/autocarehub
  DB_USERNAME: autocarehub
  JWT_EXPIRATION_MINUTES: "60"
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: local
  APP_CORS_ALLOWED_ORIGINS: http://localhost:5173,http://127.0.0.1:5173,http://localhost:8080
  SPRINGDOC_API_DOCS_ENABLED: "true"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  JAVA_TOOL_OPTIONS: -Xms256m -Xmx512m
