apiVersion: v1
kind: Service
metadata:
  name: autocarehub-postgres
  namespace: autocarehub
spec:
  type: ClusterIP
  selector:
    app: autocarehub-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
