apiVersion: v1
kind: Secret
metadata:
  name: autocarehub-secret
  namespace: autocarehub
type: Opaque
stringData:
  POSTGRES_PASSWORD: "[SUBSTITUIR_EM_AMBIENTE_REAL]"
  DB_PASSWORD: "[SUBSTITUIR_EM_AMBIENTE_REAL]"
  JWT_SECRET: "[SUBSTITUIR_POR_SEGREDO_COM_PELO_MENOS_32_BYTES]"
  EXTERNAL_SERVICE_TOKEN: "[SUBSTITUIR_POR_TOKEN_COMPARTILHADO_DOS_WEBHOOKS]"
